# Generated by Django 6.0.1 on 2026-02-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_budget_category_alter_budget_saving_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
