# Generated by Django 6.0.1 on 2026-02-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
